theme: jekyll-theme-minimal
title: Sricharani Balmuri
description: My webpage
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Sricharani Balmuri
    url: setup
  - title: Isoniazid Uptake
    url: niz
  - title: PZA Uptake
    url: pza

